# Generated by Django 5.1.1 on 2025-12-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='income',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='investment_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='risk_tolerance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskprofile',
            name='base_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='riskprofile',
            name='risk_tier',
            field=models.CharField(blank=True, choices=[('CONSERVATIVE', 'Conservative'), ('BALANCED', 'Balanced'), ('AGGRESSIVE', 'Aggressive')], max_length=20, null=True),
        ),
    ]
