# Generated by Django 5.1.1 on 2025-12-14 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RiskProfile',
        ),
    ]
