# Generated by Django 5.1.1 on 2025-11-24 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('projects_json', models.JSONField()),
                ('generated_by', models.CharField(choices=[('RULE', 'Rule Engine'), ('OPENAI', 'OpenAI'), ('LOCAL_MODEL', 'Local ML Model')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_recommendations',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('funding_target', models.DecimalField(decimal_places=2, max_digits=18)),
                ('apr_expected', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('risk_level', models.SmallIntegerField(blank=True, null=True)),
                ('expected_return_score', models.SmallIntegerField(blank=True, null=True)),
                ('liquidity_score', models.SmallIntegerField(blank=True, null=True)),
                ('min_invest_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('max_invest_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('min_invest_duration_months', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
    ]
