# Generated by Django 5.1.1 on 2025-12-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='raised',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
