# Generated by Django 5.2.12 on 2026-03-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_raised'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending Approval')], default='PENDING', max_length=20),
        ),
    ]
