# Generated by Django 5.2.12 on 2026-04-22 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_bankaccount'),
        ('projects', '0003_alter_project_status'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='bank_reference',
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.bankaccount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='external_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('STRIPE', 'Stripe'), ('BANK', 'Bank Transfer'), ('MOCK', 'Mock')], default='STRIPE', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('FUND_IN', 'Fund In'), ('FUND_OUT', 'Fund Out'), ('INVEST', 'Invest'), ('REFUND', 'Refund')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'type'], name='transaction_user_id_7b4347_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='transaction_status_505a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['stripe_payment_intent_id'], name='transaction_stripe__60a00e_idx'),
        ),
    ]
