# Generated by Django 5.2.12 on 2026-03-19 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_alter_project_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('click', 'Click'), ('save', 'Save'), ('invest', 'Invest')], max_length=20)),
                ('value', models.FloatField(default=1.0)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_interactions',
                'indexes': [models.Index(fields=['user', 'project'], name='user_intera_user_id_19cfd6_idx'), models.Index(fields=['interaction_type'], name='user_intera_interac_516669_idx'), models.Index(fields=['created_at'], name='user_intera_created_712f51_idx')],
            },
        ),
    ]
